#Hugo configuration
title = "asdfsdf"
baseURL = "https:\/\/QWER.abcd.COM"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758403"
subfolder = ""
firstpartycookies = true
cookiedomain = "abcd.COM"
